version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            docker-compose -f app/docker-compose.yml build
      - run:
          name: Run Tests
          command: |
            docker-compose -f app/docker-compose.yml run --rm gpt4cli-server go test ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
