services:
  gpt4cli-postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init-db:/docker-entrypoint-initdb.d
      - ${PGDATA_DIR}:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gpt4cli-network
  gpt4cli-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - "${GPT4CLI_DATA_DIR}:${GPT4CLI_BASE_DIR}"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@gpt4cli-postgres:5432/${POSTGRES_DATABASE}?sslmode=disable"
      GOENV: $GOENV
      GPT4CLI_BASE_DIR: $GPT4CLI_BASE_DIR

    networks:
      - gpt4cli-network
    depends_on:
      - gpt4cli-postgres
    command:
      [
        "/bin/sh",
        "-c",
        "/scripts/wait-for-it.sh gpt4cli-postgres:5432 -- ./gpt4cli-server"
      ]

networks:
  gpt4cli-network:
    driver: bridge
